apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nviypx8ib-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nviypx8ib-go 
  name: nviypx8ib-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nviypx8ib-go 
